/// Flutter icons SocialIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialIcons
///      fonts:
///       - asset: fonts/SocialIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'SocialIcons';
  static const String? _kFontPkg = null;

  static const IconData pied_piper_square = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mixer = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopify = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comments = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus_g = IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_in = IconData(0xf0e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_alt = IconData(0xf113, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xing = IconData(0xf168, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox = IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack_overflow = IconData(0xf16c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flickr = IconData(0xf16e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tumblr = IconData(0xf173, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble = IconData(0xf17d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xf17e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData foursquare = IconData(0xf180, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trello = IconData(0xf181, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gratipay = IconData(0xf184, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vk = IconData(0xf189, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weibo = IconData(0xf18a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData renren = IconData(0xf18b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pagelines = IconData(0xf18c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack_exchange = IconData(0xf18d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack = IconData(0xf198, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yahoo = IconData(0xf19e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stumbleupon = IconData(0xf1a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digg = IconData(0xf1a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pied_piper_alt = IconData(0xf1a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drupal = IconData(0xf1a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData joomla = IconData(0xf1aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance = IconData(0xf1b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify = IconData(0xf1bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deviantart = IconData(0xf1bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soundcloud = IconData(0xf1be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vine = IconData(0xf1ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codepen = IconData(0xf1cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jsfiddle = IconData(0xf1cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rebel = IconData(0xf1d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empire = IconData(0xf1d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git = IconData(0xf1d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tencent_weibo = IconData(0xf1d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qq = IconData(0xf1d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wechat = IconData(0xf1d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slideshare = IconData(0xf1e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitch = IconData(0xf1e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yelp = IconData(0xf1e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xf1ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_wallet = IconData(0xf1ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lastfm = IconData(0xf202, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ioxhost = IconData(0xf208, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angellist = IconData(0xf209, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData buysellads = IconData(0xf20d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connectdevelop = IconData(0xf20e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashcube = IconData(0xf210, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forumbee = IconData(0xf211, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leanpub = IconData(0xf212, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sellsy = IconData(0xf213, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shirtsinbulk = IconData(0xf214, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData simplybuilt = IconData(0xf215, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skyatlas = IconData(0xf216, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest_p = IconData(0xf231, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viacoin = IconData(0xf237, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gg = IconData(0xf260, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tripadvisor = IconData(0xf262, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData odnoklassniki = IconData(0xf263, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData get_pocket = IconData(0xf265, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wikipedia_w = IconData(0xf266, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData five_hundred_px = IconData(0xf26e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amazon = IconData(0xf270, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = IconData(0xf27a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData houzz = IconData(0xf27c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vimeo_v = IconData(0xf27d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData black_tie = IconData(0xf27e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reddit_alien = IconData(0xf281, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codiepie = IconData(0xf284, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modx = IconData(0xf285, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scribd = IconData(0xf28a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitlab = IconData(0xf296, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envira = IconData(0xf299, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glide_g = IconData(0xf2a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viadeo = IconData(0xf2a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viadeo_square = IconData(0xf2aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapchat_ghost = IconData(0xf2ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pied_piper = IconData(0xf2ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData first_order = IconData(0xf2b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yoast = IconData(0xf2b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData themeisle = IconData(0xf2b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quora = IconData(0xf2c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData free_code_camp = IconData(0xf2c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bandcamp = IconData(0xf2d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grav = IconData(0xf2d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData etsy = IconData(0xf2d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ravelry = IconData(0xf2d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData superpowers = IconData(0xf2dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meetup = IconData(0xf2e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accusoft = IconData(0xf369, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adversal = IconData(0xf36a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData affiliatetheme = IconData(0xf36b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData amilia = IconData(0xf36d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blogger_b = IconData(0xf37d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudsmith = IconData(0xf384, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cuttlefish = IconData(0xf38c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deskpro = IconData(0xf38f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digital_ocean = IconData(0xf391, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord = IconData(0xf392, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dochub = IconData(0xf394, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docker = IconData(0xf395, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draft2digital = IconData(0xf396, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dyalog = IconData(0xf399, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earlybirds = IconData(0xf39a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f = IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_messenger = IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firstdraft = IconData(0xf3a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData freebsd = IconData(0xf3a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitkraken = IconData(0xf3a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gofore = IconData(0xf3a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goodreads_g = IconData(0xf3a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_drive = IconData(0xf3aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gripfire = IconData(0xf3ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grunt = IconData(0xf3ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gulp = IconData(0xf3ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hubspot = IconData(0xf3b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itunes_note = IconData(0xf3b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keycdn = IconData(0xf3ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kickstarter_k = IconData(0xf3bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laravel = IconData(0xf3bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData line = IconData(0xf3c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lyft = IconData(0xf3c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magento = IconData(0xf3c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medapps = IconData(0xf3c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_m = IconData(0xf3c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medrt = IconData(0xf3c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mix = IconData(0xf3cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mizuni = IconData(0xf3cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monero = IconData(0xf3d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData napster = IconData(0xf3d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nutritionix = IconData(0xf3d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData page4 = IconData(0xf3d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patreon = IconData(0xf3d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData periscope = IconData(0xf3da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phabricator = IconData(0xf3db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pushed = IconData(0xf3e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData python = IconData(0xf3e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData red_river = IconData(0xf3e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wpressr = IconData(0xf3e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replyd = IconData(0xf3e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resolving = IconData(0xf3e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocketchat = IconData(0xf3e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rockrms = IconData(0xf3e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schlix = IconData(0xf3ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData servicestack = IconData(0xf3ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack_hash = IconData(0xf3ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speakap = IconData(0xf3f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData staylinked = IconData(0xf3f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData studiovinari = IconData(0xf3f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supple = IconData(0xf3f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telegram_plane = IconData(0xf3fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uber = IconData(0xf402, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniregistry = IconData(0xf404, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData untappd = IconData(0xf405, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ussunnah = IconData(0xf407, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaadin = IconData(0xf408, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viber = IconData(0xf409, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vnv = IconData(0xf40b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xbox = IconData(0xf412, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autoprefixer = IconData(0xf41c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gitter = IconData(0xf426, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strava = IconData(0xf428, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stripe = IconData(0xf429, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flipboard = IconData(0xf44d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weebly = IconData(0xf5cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kaggle = IconData(0xf5fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suse = IconData(0xf7d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airbnb = IconData(0xf834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battle_net = IconData(0xf835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData evernote = IconData(0xf839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData waze = IconData(0xf83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yammer = IconData(0xf840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData git_alt = IconData(0xf841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
